# Site settings
title: Nistara Randhawa # type your own lablog title here

description: > # this means to ignore newlines until "baseurl:"
  Veterinary science, programming, and the One Health Approach
baseurl:  # the subpath of your site, e.g. /blog/
url: http://nistara.net # the base hostname & protocol for your site
include: [ _assets , _projects ]

name : 
email :
github_username: nistara
twitter_username: 
website : nistara.github.io

# Build settings
markdown: kramdown
kramdown:
  input: GFM

noindex:  # if true, google will ignore your pages!

defaults:   # overwrite with in YAML frontmatter, e.g. 'place: New York'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      place:  # default Geolocation of posts.
      author: # default author for posts (for multi-authoring)
      
# Generating sitemaps:
gems:
  - jekyll-sitemap
